### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by meditans** [music-suite/music-pitch-literal#7]
Hi, here are some ideas we could use to improve the reading of the haddocks for this package.
This package is fairly simple, so there's not much to do, but:
- In the laws for the alterable class there is a mention to the `accidental` function, which is not documented, and not present in the Index of this package.
- In the `Alterable` instances, it's not clear from the documentation what's the semantic meaning of some of the instances (like, `Double`, or `(b -> a)`). This could be better explained in the documentation for the class. 
- Same thing for the `Augmentable` class.
- Maybe a better name for the `IsPitch` class would be `FromPitch` (I'm divided on this)?
- Also, the instances here are a bit opaque.. what's the expected usecase for `IsPitch (Fixed a)`, for example?
- The `PitchL` constructor should be given more explanation: it's not clear what the triple means, from the haddock. To obtain this purpose, it would be sufficient to display the comment in the source as part of the haddock, and adding some examples. 
- Same concerns for the `Interval` type. Are those generalized instances useful enough to justify the added barrier in annotating and using the literal values? If the answer is in fact yes, we might want to provide some examples in the haddock.

These are the most important things to document in my opinion. In a second pass, we could create a little `Tutorial` module, in the style of Gabriel Gonzales libraries (eg turtle). I can quicky implement the features you are ok with, and make a PR.

**Comment by hanshoglund** [comment]
Feel free. Some points:

- `IsPitch` is the convention used by other overloaded things in base, such as `IsString`, `IsList` etc

- The separation of `PitchL` vs `Pitch` etc is purely technical, it's due to the fact that some packages depend on `music-pitch-literal` but not on `music-pitch` [*](https://github.com/music-suite/music-docs/blob/master/music-suite-deps.png), so the `Pitch` type can not be used to define the literals. I'm actually 99% sure I'm going to to merge these packages as the complexity is really not worth it. Then the type would simply be `IsPitch a => fromPitch :: Pitch -> a`, similar to `fromString :: IsString a => String -> a`.

- IIRC The numeric instances all generate "MIDI"-style pitch (throwing away the spelling) for convenience.

**Comment by meditans** [comment]
Hi,

I understand the motivations between the `IsPitch` pattern, and now I'm able to explain better what I feel to be the difference between this and how it's used into the standard libraries. For strings, both a text `"foo"` and a string `"foo"` "mean" exactly the same thing, but they happen to have different encodings. The convenience of the `IsString` typeclass is to avoid boilerplate converting back and forth from isomorphic objects who happen to have different internal representation.

In this library, however, a thing like `([String], [Last (Ratio Integer)])` is a pitch, so there isn't an isomorphism between a "real" Pitch like `PitchL` and a arbitrary `IsPitch` structure, and for now I'm struggling to see what we got in return for muddling the semantic waters. I feel the correct paragon would be to say that we should have instances like:

    instance IsString a => IsString (Maybe a) where ...
    instance IsString a => IsString [a] where ...
    instance (Monoid a, IsString b) => IsString (a,b) where ...

I'll find the name `IsString` confusing in that case too.

I see the merit in having the `Int` instance for Midi conversion, though.

What do you think of the above point? Could you explain the merit of having this generic instances? Could they be standalone functions, instead, with more precise semantics?

**Comment by hanshoglund** [comment]
These instances are surprisingly an essential part of how Music Suite works, so I will go into some detail with this reply. I haven’t made any real attempt to describe this before, as it is more relevant to developers than users, but here we go.

### Lifted monoids and literals

First, we are going to assume we have a pair/writer and function/reader monad and applicative instances in scope. As you probably know these are essentially the same as `Reader` and `Writer` in mtl/transformers except for the newtype wrapper.

```hs
instance Monoid r => Applicative ((,) r)
instance Monoid r => Monad ((,) r)
instance Applicative ((->) r)
instance Monad ((->) r)
```

Second, note that any Monoid can be lifted through an applicative as follows.

```hs
instance (Applicative f, Monoid a) => Monoid (f a) where
  mempty = pure mempty
  mappend = liftA2 mappend
```

As a matter of fact this not only works for `Monoid`, but for any operation on a single type `a -> a -> ... -> a`, so we could lift i.e. the standard numeric classes in a similar way. Whether or not you should define such instances is [a matter of some discussion](http://failex.blogspot.co.uk/2015/10/the-uninteresting-monoids-of-certain.html). In this case we are only going to care about literals.

What does monoids has to do with literals? Answer: `mempty` can be thought of as a literal for `0`, and more generally we can lift any literal into an applicative using pure.

```hs
instance (Applicative f, Num a) => Num (f a) where
  fromInteger = pure . fromInteger
instance (Applicative f, IsString a) => IsString (f a) where
  fromString = pure . fromString
```

This machinery is the basis of the instances you define above (using the maybe applicative, list applicative and writer applicative respectively). As you point out, these instances are potentially confusing and the standard library is inconsistent about whether to include them or not.

I think at least part of this confusion stems from the fact that we use monads/applicatives to represent both effects, such as `IO` and values such as `(r ->)`. IMHO many interesting uses of applicatives (FRP, probabilistic programming, logic programming) depends on the fact that the applicative wrappers are used to values that are semantically different from numbers/strings but still obeys the same laws (i.e. we always expect `2 + 3 = 5` whatever 2,3 and 5 is overloaded to mean. This is nothing new in mathematics, think of complex numbers and matrices for example.

IMO way to avoid "muddling the semantic" waters as you describe above may be to be very clear about the laws for our literal types, as with any type class. `ByteString` and `String` are not semantically the same, nor is (nor is `[]` and `Set` with the new `OverloadedLists` extension), but we do expect certain relationships to hold, in this case `x == unpack (fromString x)`.

### What does this have to do with music?

Music Suite is an attempt to answer the question:

> Can we have a functional/typed definition of music that is not tied to a particular musical notation system, but is still powerful enough to express any type of music?

In the context of Haskell this translates to "what types can be used to meaningfully represent music or aspects of music, and what operations can we define on these types?". The plural is crucial here: most (all?) traditional CM systems pick a single type `Music :: *` and define all other operations in relation to that type, in Music Suite we want to define music as a set of type constructors that are eventually applied to create the final music representation, and then define our operations generically over these types.

Music Suite makes a couple of assumptions about these representations:

- We assume that a music representation is composed out of a finite set of *musical aspects*, such as pitch, time, dynamics, instrument, articulation, space and so on.
- We assume that different users/musical styles may want to choose more complex or simple representations for various aspects. I.e. Indian classical music needs a more complex pitch representation, West African music needs a more complex rhythm representation and so on.
- We assume (for simplicity) that time is somewhat different from the other types. While, i.e. pitch is often handled by a very specific type, we assume that time can almost always be treated as relations between rational numbers, with extra information about "where the barlines are" stored separately at the top-level.


### Music Suite representation

This leads us to the internal representation used in Music Suite, which is based on a series of basic "time types" (i.e. `Time`, `Duration`, `Span`, kind `*`), "time transformers" (i.e. `Note`, `Voice`, `Score`, kind `* -> *)` and "aspect transformers" (i.e. `PitchT`, `ArticulationT`, kind `* -> *`). The time constructors describe how a value take place over time (similar to FRP but non-interactive), while the aspect transformer all add some musical aspect to its underlying type.

As you probably have noticed by this point, the time transformers are all based on the monad/applicatives described above, i.e. reader, writer and list.

```hs
newtype Behavior a = Time -> a        -- Applicative, Monad
newtype Note a     = (Duration, a)    -- Applicative, Monad
newtype Event a    = (Span, a)        -- Applicative, Monad
newtype Score a    = [Event a]        -- Applicative, Monad
...
```
The aspect transformers are all essentially the writer monad with an associated pair of classes that allow us to traverse/update and view them, i.e. `HasArticulation(s)`. We also include `Maybe` and `[]` here to allow representation of things such as rests and chords. The idea here is of course that aspect transformers can be composer to give us a type with multiple musical aspects.

```hs
newtype PitchT p r        = (p, r)    -- Applicative, Monad
newtype ArticulationT a r = (a, r)    -- Applicative, Monad

type MyMusicalType = ArticulationT MyArticulation (PitchT MyPitch ())
```

#### Creating musical values

So we have a typed representation of musical data over time, but how do we create and access these values without resorting to lots of explicit construction/pattern matching? Let's start by assuming that we do not care about pitch, but do care about loudness, instrument and time, for example to represent a basic drum pattern.


```hs
newtype Loudness = Average Double deriving Monoid -- assuming a relative dynamic scale such as dB

data DrumType = Tom | Kick | Snare
instance Monoid DrumType where mempty = Snare -- arbitrary default

type MyNoteType = DynamicsT Loudness (PartT DrumType ())
type MyRhythmType = Score MyNoteType
rh :: MyRhythmType
rh = ...?
```

How do we construct `rh` here? It turns out `MyRhythmType` is automatically a monoid so we can just say `mempty`! What kind of value does this give us?

```hs
>>> mempty :: MyRhythmType
[(0<->1, DynamicsT (Average 0, PartT (Snare, ())))^.event]^.score
```

Not very readable, but it all makes sense as what we have is just a sequence of default (mempty) values. The way it works is:

- The `Score` lifted instance decides to create a default "note" in the default time span
  - The default time span is the time between the default offset (0) and the default duration (1)
- The default of `MyNoteType` is the same as the default of `DynamicsT`
  - The default of a `DynamicsT` (the writer monad) is the default of the dynamic type and the default of the rest
    - The default loudness value is 0 (wrapped in the average monoid)
    - The default of a `PartT` (the writer monad) is the default of the part type and the default of the rest
      - The default part is (arbitrarily) `Snare`
      - The default of `()` is `()`

What if we want to use non-default values? In the case of the aspects (here: dynamics and part) we use the associated `Traversal`, and it all works as expected.

```hs
rh = set parts Kick $ mempty
rh = parts .~ Kick $ mempty
rh = dynamics +~ 2 $ part .~ Kick $ mempty
```

In this case, the lens library looks for the traversal `parts`, and needs to find an instance of `HasParts`. It then finds in turn (simplified):

- `HasParts a => HasParts (Score a)`
- `HasParts a => HasParts (DynamicsT _ a)`
- `HasParts (PartT p _)`

We need to use the plural form "parts", as the singular form (with a lens) is not defined on scores.

To use non-default time values, we will of course exploit the `Transformable` instance of `Score`, or derived methods such as `delay`, `stretch`, `pcat` etc.


#### Adding pitch

The above example works fine, but what if we want to express something like a fugue (pitch and integral parts)? In this case we need to replace the `()` at the bottom of the stack with a pitch type.

```hs
import Music.Pitch(Pitch)

newtype Loudness = Average Double deriving Monoid
newtype FuguePart = Sum Int deriving Monoid -- Use Sum to get 0 as default

type MyNoteType = DynamicsT Loudness (PartT FuguePart Pitch)
type MyScoreType = Score MyNoteType
fugue :: MyScoreType
fugue = ...?
```

In this case the `mempty` trick won't work, as there is (very reasonably) no way of defining a default pitch (we could pick an arbitrary value as with the parts above, but the best thing this would give us is `mempty, up M2 mempty, up M3 mempty, mempty`, which is rather more difficult to read than `c,d,e,c`).

Luckily, as we have seen above, the general lifting pattern applies to any literal-like type, not just to monoids. So if we write `c` instead of `mempty` it will trigger a lookup of the `IsPitch` instance similar to the lookup of `Monoid` above. Note that all non-pitch values will still be derived from the monoid instance, so when we write `c` we really just mean, give me a `c` with all the other aspects values for this type being the defaults. The whole sequence is:

- The `Score` instance decides to create C in the default time span
- The C of `MyNoteType` is the same as the C of `DynamicsT`
  - The C of a `DynamicsT` (the writer monad) is the default of the dynamic type and the C of the rest
    - The default loudness value is 0 (wrapped in the average monoid)
    - The C of a `PartT` (the writer monad) is the default of the part type and the C of the rest
      - The default part is `Sum 0`
      - The C of pitch is C

Again, we can use the lenses/traveersals to update all other elements, so expressions like the following work

```hs
[soprano, alto, tenor, bass] = [0..]

fugue = pcat
  [ part .~ soprano $ scat [c..g] |/ 2
  , part .~ alto $ c |> d |> (dynamics +~ 2 e)
  ]
```

### Consequences

All in all this gives us the way of expressing various music representation and still have a terse expression language for constructing and manipulating these values.

As a clincher, consider some of the basic examples in the User Guide, and how these would read without the lifted literals instances (here I am actually *removing* some `pure`s):

```hs
c |> d |> e
==>
pure (pure (pure (pure c))) |> pure (pure (pure (pure d))) |> pure (pure (pure (pure e)))


stretch (1/4) $ scat [c..a]|/2 |> b |> c'|*4
==>
stretch (1/4) $ scat [pure (pure (pure (pure c)))..(pure (pure (pure (pure a))))]|/2 |> pure (pure (pure (pure b))) |> pure (pure (pure (pure c'))) |*4
```

### Bonus chapter: Simplifying the note transformer stack

Of course, for a "common music notation" score this way of encoding the aspect quickly becomes [very tedious](https://github.com/music-suite/music-preludes/blob/master/src/Music/Prelude/Standard.hs#L64), which is why I would in fact like move away from big note transformer stacks. Arguably things like color and other presentational information could be put into a separate dynamic meta type (we already do this for scores), making the final stack something more like.

```hs
type StandardNote = AddMeta (PartT Part (ArticulationT Articulation (DynamicT Dynamics Pitch)))
type Music = Score StandardNote
```

Another viable alternative to note transformers would be extensible records, i.e. using [this new library](https://nikita-volkov.github.io/record/). The way the library is used using the mempty/literals and lensified such as `pitch`, `part` etc would still remain, but the type singatures would be nicer.

**Comment by hanshoglund** [comment]
Closing, as this package is now deprecated. Copied the essay over here: https://gist.github.com/hanshoglund/68b06c43823459d0c816
